### PR TITLE
Pull request for test task : Itera Research Kharkov

### PR DESCRIPTION
**Pull request by stanislav-web**
Please see INSTALL.md

### CODE REVIEW

**Comment by stanislav-web** [comment]
Update schema DB docs/quiz.sql

**Comment by stanislav-web** [comment]
Is this proposal still relevant?
I wait a week for verification. But if its not relevant , please tell  to your HR or me ... Since she can't  gave me a clear answer.

Кароче говоря, я ждать еще неделю не буду

**Comment by stanislav-web** [comment]
Is this proposal still relevant?
I wait a week for verification. But if its not relevant , please tell  to your HR or me ... Since she can't  gave me a clear answer.

Кароче говоря, я ждать еще неделю не буду

**Comment by jagermesh** [comment]
Hello!

Here are some comments. Unfortunately I was unable to fully test the project because it's not working.

1) Project not working, both pages gives error

http://test.local.com/index.php?controller=quiz&action=create
Quiz\Exceptions\RouterException: [404]: Route does not found

Quiz\Exceptions\RouterException: [404]: Route does not found
http://test.local.com/index.php?controller=quiz&action=list

2) Code is OVER complicated as for such a simple project.

3) Work took too much time, average people spent for this is 16hrs.

4) Wrong data types for PK in tables - SMALLINT is simply too small for any project.

5) Wrong CASCADE in FK - if there are scores - user should not be able to delete quiz and questions. It lead to loosing important student data.

6) I don't like the idea of using ENUMs for dictionaries (status in your project)

HR will contact you in regards to your application.

**Comment by stanislav-web** [comment]
> 1. Project not working, both pages gives error
// Very strange )) but I have no idea what your problems are.. The server may not be configured

> 2. Code is OVER complicated as for such a simple project. 
// Yes, i agree

> 3. Work took too much time, average people spent for this is 16hrs.
// I dont like to use Frmwrks (i like creating) , and the test does not provide how much time it takes

> 4. Wrong data types for PK in tables - SMALLINT is simply too small for any project
// What ?? SmallInt has 65535 ) and also this is "simple project" 

> 5. Wrong CASCADE in FK - if there are scores - user should not be able to delete quiz and questions. It lead to loosing important student data. 
// Also it could be described in README ) 

> 6. I don't like the idea of using ENUMs for dictionaries (status in your project)
// ENUM = 1-2 bytes ) PROCUDURE ANALYSE from Percona will show what field type will be prefered.
Enum there is more logical and safer

... Ok, thanks ... I did the conclusion for self

**Comment by jagermesh** [comment]
Server configured, main page working fine.

As for FK and README, I was looking for smart guy, who able to analyze rewuirements and predict what users must be able to do and what they shouldn't.

SMALLINT is small, we have 500k records in our quiz table and probably 100 billions in scores.

Calm dowm and move on, the way you speak give me impression that you don't like critics. That's wrong attitude :)

Pleade don't be upset, you did a great job, it just don't meet some of our expectations.

I wish you all the best.

**Comment by stanislav-web** [comment]
Anyway, thanks,
it's hard to do something without knowing what some want from you
 i think I'm not suitable for this job

**Pull request closed without merging**
